version: "3"
services:
  myapitemplate:
    build:
      context: ./
      dockerfile: release.Dockerfile
    container_name: myapitemplate
    restart: always
    env_file:
      - app/dev.env
    volumes:
      - "./app:/app"
    ports:
      - "90:90"